### ISSUE TITLE
Display 'no permissions' instead of blank page

### ISSUE THREAD

**Issue by xeoth** [Marilyth/Mops-WebInterface#6]
So right now when you don't have permissions to add trackers to a server, it displays an empty page. It'd be cool if it showed something like "No permissions."

**Comment by Marilyth** [comment]
Definitely something I plan to add, at some point.
You do see all existing trackers, in case there are some, even if you don't have permission to add/remove/update them. We are just skipping the "+New+" section which makes it empty in case there are none

**Comment by Marilyth** [comment]
This has been adressed.

It will now show a red section "No permission to add tracker!" or a green section "Add Tracker", depending on whether you have the required permissions or not.
